version: "3"

services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: yobasystems/alpine-mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./sql/uuid_table.sql:/docker-entrypoint-initdb.d/uuid_table.sql
      - ./sql/uuid_primary.sql:/docker-entrypoint-initdb.d/uuid_primary.sql
      - ./sql/uuid_primary_optimized.sql:/docker-entrypoint-initdb.d/uuid_primary_optimized.sql
